# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  - main

pool:
  vmImage: "ubuntu-latest"
  strategy:
  matrix:
    Python38:
      python.version: "3.8"
    Python39:
      python.version: "3.9"

steps:
  - script: pip install -e ".[development]"
    displayName: "Install requirements"

  - script: |
      python -m pip install --upgrade pip
      python -m pip install pylint
      python -m pylint --disable=all -e W0311 --jobs=0 --indent-string='    ' **/*.py
    displayName: "Run lint tests"

  - script: |
      pip install pytest pytest-azurepipelines
      pip install pytest-cov
      pytest --doctest-modules --junitxml=junit/test-results.xml --cov=. --cov-report=xml
    displayName: "pytest"
